# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "CentOS-6.3_i386"
  # config.vm.box_url = "http://domain.com/path/to/above.box"
  # config.vm.network :hostonly, "192.168.33.10"
  # config.vm.network :bridged
  config.vm.forward_port 5672, 5672
  # config.vm.share_folder "v-data", "/vagrant_data", "../data"
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
		puppet.module_path = "modules"
  end
end
